name = "NiLog"
uuid = "07b9913f-4636-4bc8-9841-9af50769c5b0"
authors = ["GiggleLiu"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
